name: flutter_data_setup_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  flutter_data: ^1.0.0
  flutter_riverpod: ^1.0.0
  get_it: ^7.0.0
  json_annotation: ">=4.3.0 <4.4.0"
  path_provider: ^2.0.2
  provider: ^5.0.0

# dependency_overrides:
#   flutter_data:
#     path: ../flutter_data

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
